on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  kindlefy:
    runs-on: ubuntu-latest
    name: Sync kindle rss.
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Kindlefy
        uses: gbkel/kindlefy@v1.3.5
        with:
          kindle_email: ${{ secrets.KINDLEFY_KINDLE_EMAIL }}
          sender: ${{ secrets.KINDLEFY_SENDER }}
          sources: '[]'
          storage: '[{ "type": "local", "githubAccessToken": "${{ secrets.GITHUB_TOKEN }}" }]'
          no_duplicated_sync: true
