on:
  schedule:
    - cron: '0 1 * * SAT'

jobs:
  kindlefy:
    runs-on: ubuntu-latest
    name: Sync kindle manga.
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Kindlefy
        uses: gbkel/kindlefy@v1.1.9
        with:
          kindle_email: ${{ secrets.KINDLEFY_KINDLE_EMAIL }}
          sender: ${{ secrets.KINDLEFY_SENDER }}
          sources: '[{ "type": "manga", "name": "One Piece", "count": 1 }]'